PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ccf: <http://purl.org/ccf/>

CONSTRUCT {
    ?cell_type ccf:count ?count .
}
FROM <https://purl.org/ccf/releases/2.2.1/ccf.owl> # Ontology / CCF.OWL
WHERE {
    SELECT DISTINCT ?cell_type (COUNT(?cell_type) as ?count)
    WHERE {
        ?sample ccf:has_registration_location ?rui_location ;
                ccf:generates_dataset ?dataset ;
                ccf:comes_from ?tissueDonor .

        ?rui_location a ccf:SpatialEntity ;
                    ccf:collides_with ?annotation .
        ?cell_type ccf:ccf_located_in ?annotation .

        ?tissueDonor ccf:sex ?sex ;
                     ccf:age ?age ;
                     ccf:bmi ?bmi ; 
                     ccf:tissue_provider_name ?tmc .
        ?dataset ccf:technology ?technology .
            #{{FILTER}}
    }
    GROUP BY ?cell_type
    ORDER BY DESC(?count)
    

}
