PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ccf: <http://purl.org/ccf/>
CONSTRUCT {
    ?annotation ccf:count ?count .
}
WHERE {
  SELECT ?annotation (COUNT(?annotation) as ?count)
  WHERE {

    ?sample ccf:has_registration_location ?rui_location ;
            ccf:generates_dataset ?allTech ;
          ccf:comes_from ?tissueDonor .  
    ?rui_location a ccf:SpatialEntity ;
                  ccf:collides_with ?annotation .
    
    ?tissueDonor ccf:sex ?sex ;
                ccf:age ?age ;
                ccf:bmi ?bmi ;
                ccf:tissue_provider_name ?tmc .
    
    ?allTech ccf:technology ?technology .

    #{{FILTER}}
  }
  GROUP BY ?annotation
  ORDER BY DESC(?count)
}
