PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ccf: <http://purl.org/ccf/>

SELECT DISTINCT ?annotation (COUNT(?annotation) as ?count)
WHERE {
  #{{top_filter}}
  #{
    #VALUES (?annotation) {
      #(<http://purl.obolibrary.org/obo/UBERON_0000955>)
    #}
  #}

  ?sample ccf:has_registration_location ?rui_location ;
          ccf:generates_dataset ?allTech ;
  		  ccf:comes_from ?tissueDonor .  
  ?rui_location a ccf:SpatialEntity ;
                ccf:collides_with ?annotation .

  ?tissueDonor ccf:sex ?sex ;
               ccf:age ?age ;
               ccf:bmi ?bmi .

  
  ?allTech ccf:technology ?technology .
  
  
  FILTER (?sex = "$sex")
  FILTER (?age > $minAge && ?age < $maxAge)
  #FILTER (?bmi > $minBMI && ?bmi < $maxBMI)
  
  FILTER(?annotation IN (<$ontologyTerms>))

  # Filter by technologies
  #FILTER (?technology IN ("LC"))
  
}
GROUP BY ?annotation ?sex ?age 